-- Schema for Simple POS
CREATE TABLE IF NOT EXISTS produk (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  harga DECIMAL(12,2) NOT NULL DEFAULT 0,
  stok INT NOT NULL DEFAULT 0,
  gambar VARCHAR(255),
  deskripsi TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (nama)
);

CREATE TABLE IF NOT EXISTS transaksi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kode VARCHAR(30) NOT NULL UNIQUE,
  tanggal DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  subtotal DECIMAL(12,2) NOT NULL,
  pajak DECIMAL(12,2) NOT NULL,
  grand_total DECIMAL(12,2) NOT NULL,
  jumlah_bayar DECIMAL(12,2) NOT NULL,
  kembalian DECIMAL(12,2) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (tanggal)
);

CREATE TABLE IF NOT EXISTS transaksi_detail (
  id INT AUTO_INCREMENT PRIMARY KEY,
  transaksi_id INT NOT NULL,
  produk_id INT NOT NULL,
  harga DECIMAL(12,2) NOT NULL,
  qty INT NOT NULL,
  total DECIMAL(12,2) NOT NULL,
  FOREIGN KEY (transaksi_id) REFERENCES transaksi(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (produk_id) REFERENCES produk(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
